version: '3.3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80' # Mapping the Nginx port to host machine's port 80