apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: f1-app
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: <image_url>
        imagePullPolicy: Always
        env:
          - name: VITE_API_URL
            value: <api_url>
        ports:
        - containerPort: 80
